semi: false
singleQuote: true
trailingComma: none
arrowParens: avoid
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrder: ['^node:', '<THIRD_PARTY_MODULES>', '^[.$]']
